### ISSUE TITLE
Where is the actual .ane file?

### ISSUE THREAD

**Issue by psvdwal** [myflashlab/alarmManager-ANE#2]
I can download the zip file but do not see the actual .ane file for use in Adobe Flash CS6... 

What should i do to use the ANE in a Flash Professional project?

**Comment by myflashlab** [comment]
look inside the lib folder. the ane file is there.

**Comment by psvdwal** [comment]
..sorry for asking, but where can I find the lib filder. I do not see it in the downloaded zip-file...
