### ISSUE TITLE
I have a question about Alarm Manager Ane.

### ISSUE THREAD

**Issue by KangPrince** [myflashlab/alarmManager-ANE#3]
Hi, there.
How can an app built by the alarm manager ane be lunched by the alarm event ?
When I go to bed, I set alarm app, and turn off alarm app.
In the morning, Alarm app should turn on on time.

The notification function is very good, but I need one more function - lunching by the alarm event. 

And,
Would you tell me about the followings.
alarmTask.setOngoing(false);
alarmTask.setOnlyAlertOnce(false);

Thanks.
Regards.

**Comment by KangPrince** [comment]
Would you tell me about the followings.
alarmTask.setOngoing(false);
alarmTask.setOnlyAlertOnce(false);

**Comment by KangPrince** [comment]
And 
alarmTask.setSound(File.documentsDirectory.resolvePath("sound01.mp3"));
Is that right ?

**Comment by KangPrince** [comment]
I need a function, auto app execution when the alarm goes off.
Regards.

**Comment by myflashlab** [comment]
> alarmTask.setOngoing(false);

read here http://developer.android.com/reference/android/app/Notification.Builder.html#setOngoing%28boolean%29

> alarmTask.setOnlyAlertOnce(false);

http://developer.android.com/reference/android/app/Notification.Builder.html#setOnlyAlertOnce%28boolean%29

opening the app is not supported on this ane version. for custom work orders, please drop us an email from myappsnippet.com
