### ISSUE TITLE
The Function - Opening App.

### ISSUE THREAD

**Issue by KangPrince** [myflashlab/alarmManager-ANE#4]
Hi, there.
I think that Alarm apps have the function that open app on time.
But alarmManager-ANE can't open app.
Bye.

**Comment by myflashlab** [comment]
The alarmManager ANE is a base for calling different tasks when the Air app is closed and considering that if when the Air app is closed, your AS3 code cannot run, we are restricted to build the tasks in native code.

as the current version as seen in the demo ANE here in GitHub, we have only the following tasks considered:

```actionscript
import com.myflashlab.air.extensions.timerTask.alarmTypes.Alarm_Notification;
import com.myflashlab.air.extensions.timerTask.alarmTypes.Alarm_ShowToast;
import com.myflashlab.air.extensions.timerTask.alarmTypes.Alarm_SimpleDispatch;
```

many different tasks can be added in future versions but we can go with building them only based on devs requests. for other requests that few or one dev needs, you can ask for custom ANE orders. please check here: http://www.myflashlabs.com/contact/
